Repository Team138Entropy/Entropy2021, pull requests merged in 2020-11, with the labels that each got.

#21 Add to readme
  gradlew
  readme.md
Labels: meta

#29 Add dependabot (version updates)
  .github/dependabot.yml
Labels: low priority

#37 Im tired of the branch name it was funny at first but im done with it
  vision/EV.py
  vision/EVBall.py
  vision/EVBallFinder.py
  vision/EVFeederStation.py
  vision/EVHighGoal.py
  vision/EVHighGoalFinder.py
Labels: enhancement
